export type Language = { code: string; name: string };

export const languages: Language[] = [
  { code: 'Alb', name: 'Albanian' },
  { code: 'Ara', name: 'Arabic' },
  { code: 'Bra', name: 'Brazilian Portuguese' },
  { code: 'Chi', name: 'Chinese' },
  { code: 'ChS', name: 'Simplified Chinese' },
  { code: 'SChi', name: 'Simplified Chinese' },
  { code: 'ChT', name: 'Traditional Chinese' },
  { code: 'TChi', name: 'Traditional Chinese' },
  { code: 'Cro', name: 'Croatia' },
  { code: 'Dan', name: 'Danish' },
  { code: 'Dut', name: 'Dutch' },
  { code: 'Eng', name: 'English' },
  { code: 'Fin', name: 'Finnish' },
  { code: 'Fre', name: 'French' },
  { code: 'Ger', name: 'German' },
  { code: 'Gre', name: 'Greek' },
  { code: 'Heb', name: 'Hebrew' },
  { code: 'Ita', name: 'Italian' },
  { code: 'Jap', name: 'Japanese' },
  { code: 'Kor', name: 'Korean' },
  { code: 'Lat', name: 'Latvian' },
  { code: 'Lit', name: 'Lithuanian' },
  { code: 'Nor', name: 'Norwegian' },
  { code: 'Pol', name: 'Polish' },
  { code: 'Por', name: 'Portuguese' },
  { code: 'Rom', name: 'Romanian' },
  { code: 'Rum', name: 'Romanian' },
  { code: 'Rus', name: 'Russian' },
  { code: 'Ser', name: 'Serbian' },
  { code: 'Spa', name: 'Spanish' },
  { code: 'Swe', name: 'Swedish' },
  { code: 'Tai', name: 'Thai' },
  { code: 'Tur', name: 'Turkish' },
  { code: 'Uru', name: 'Uruguay Spanish' },
];
